// Auto-update (M5.3) via electron-updater against GitHub Releases. The publish
// feed comes from app-update.yml (generated by electron-builder from the
// `publish` config). Updates only run in a packaged, signed build — in dev /
// unpackaged we report 'none'. State is streamed to the renderer on app://update.

import { app, type WebContents } from 'electron'
import electronUpdater from 'electron-updater'

import type { UpdateState } from '../shared/types'
import { logRendererError } from './logging'

const { autoUpdater } = electronUpdater

let state: UpdateState = { status: 'idle', version: null, message: null, percent: null }
let sender: WebContents | null = null

function emit(next: Partial<UpdateState>): void {
  state = { ...state, ...next }
  if (sender && !sender.isDestroyed()) sender.send('app://update', state)
}

export function currentUpdateState(): UpdateState {
  return state
}

/** Wire the updater to a window's webContents (call once after the window loads). */
export function initUpdater(wc: WebContents): void {
  sender = wc
  autoUpdater.autoDownload = true
  autoUpdater.autoInstallOnAppQuit = true

  autoUpdater.on('checking-for-update', () => emit({ status: 'checking', message: null }))
  autoUpdater.on('update-available', (i) => emit({ status: 'available', version: i.version }))
  autoUpdater.on('update-not-available', () => emit({ status: 'none' }))
  autoUpdater.on('download-progress', (p) =>
    emit({ status: 'downloading', percent: Math.round(p.percent) })
  )
  autoUpdater.on('update-downloaded', (i) =>
    emit({ status: 'ready', version: i.version, percent: 100 })
  )
  autoUpdater.on('error', (e) => {
    const message = e instanceof Error ? e.message : String(e)
    logRendererError(`updater: ${message}`)
    emit({ status: 'error', message })
  })
}

/** Check the Releases feed. No-op (status 'none') in unpackaged/dev builds. */
export async function checkForUpdate(): Promise<void> {
  if (!app.isPackaged) {
    emit({ status: 'none', message: 'auto-update runs only in packaged builds' })
    return
  }
  try {
    await autoUpdater.checkForUpdates()
  } catch (e) {
    emit({ status: 'error', message: e instanceof Error ? e.message : String(e) })
  }
}

export function quitAndInstall(): void {
  autoUpdater.quitAndInstall()
}
